version: 1.0.0-build-{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  SITE_NAME: build-with-appveyor
  FTP_PASSWORD:
    secure: U1fuLaWVY3EpZe0jWlDkkvmWEG8xhf8iQ6fk7pNVz7Q5yx6EX37z0IorrgLRpzdwjqJLr5oO5CocUl332sd7Lw==
  GITHUB_USERNAME: JuergenGutsch
  GITHUB_PASSWORD:
    secure: w8+bqxuEUHy6VQT9ZtSoyw==
  REPOSITORY_NAME: unittesting-aspnetcore
install:
- cmd: dotnet restore WebApiDemo.sln
build_script:
- cmd: dotnet build WebApiDemo
test_script:
- cmd: dotnet test WebApiDemo.Tests
deploy_script:
- ps: .\deploy-to-azure.ps1